### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

### ISSUE THREAD

**Issue by yancccc** [Nalorokk/ultracam#1]
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by Nalorokk** [comment]
Updated readme, must be possible to run it now.

**Comment by yancccc** [comment]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 46 column 13 (char 628)

**Comment by Nalorokk** [comment]
It is probably something with JSON syntax goes wrong in your config. I will update this soon to work without any config.json, and possibility to configure it from web UI.

**Comment by Nalorokk** [comment]
This issue is fixed radically in #d5df125077329c85f4da31fdcf19fea93cef0895
